# Generated by Django 3.2.3 on 2021-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coppone_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' نام به لاتینی باشد')),
                ('max_used', models.IntegerField(verbose_name='تعداد')),
                ('current_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد استفاده شده ')),
                ('percent', models.IntegerField(default=9, verbose_name='درصد تخفیف')),
                ('can_used', models.IntegerField(verbose_name='توان استفاده هر شخص از این کد')),
                ('active', models.BooleanField(default=True, verbose_name=' فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='refid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
