# Generated by Django 3.2.3 on 2021-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_comments', '0002_auto_20210629_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
    ]
