# Generated by Django 3.2.3 on 2021-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_comments', '0003_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و وقت ویرایش شده'),
        ),
    ]
