# Generated by Django 3.2.3 on 2021-06-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_auto_20210617_1414'),
        ('eshop_favorate', '0002_auto_20210617_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorateitemdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول'),
        ),
    ]
