# Generated by Django 3.2.3 on 2021-05-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0005_auto_20210510_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProductCategory',
        ),
    ]
