# Generated by Django 3.2.3 on 2021-05-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0010_alter_productcategory_subproductcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='SubProductCategory',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='tree_id',
        ),
    ]
