# Generated by Django 3.2.3 on 2021-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0012_productcategory_subproductcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='SubProductCategory',
            field=mptt.fields.TreeForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cildren', to='eshop_products_category.productcategory'),
        ),
    ]
