# Generated by Django 3.2.3 on 2021-06-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_auto_20210617_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_maker',
            field=models.TextField(default=1, verbose_name='درباره سازنده'),
            preserve_default=False,
        ),
    ]
