# Generated by Django 3.1.5 on 2021-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitetitle', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=500, verbose_name='ادرس')),
                ('telephone', models.CharField(max_length=50, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(max_length=50, verbose_name='تلفن همراه')),
                ('fax', models.CharField(max_length=50, verbose_name='فکس')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل سایت')),
            ],
            options={
                'verbose_name': 'تنضیمات سایت',
                'verbose_name_plural': 'مدریت تنضیمات',
            },
        ),
    ]
