# Generated by Django 3.1.5 on 2021-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='location_img',
            field=models.ImageField(default=1, upload_to='locations_images/'),
            preserve_default=False,
        ),
    ]
