# Generated by Django 3.1.5 on 2021-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_auto_20210525_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن یا نبودن'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(default=1, upload_to='setting_images/', verbose_name='لوگو سایت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(verbose_name='درباره سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='location_img',
            field=models.ImageField(upload_to='locations_images/', verbose_name='عکس لوکیشن مورد نظر'),
        ),
    ]
