# Generated by Django 3.2.3 on 2021-06-30 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_comments', '0004_comments_edited_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
    ]
