# Generated by Django 3.2.3 on 2021-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favorate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorateitem',
            options={'verbose_name': 'محصول مورد علاقه', 'verbose_name_plural': 'محصولات مورد علاقه\u200d'},
        ),
        migrations.AddField(
            model_name='favorateitemdetail',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
