# Generated by Django 3.2.3 on 2021-06-23 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_auto_20210617_1414'),
        ('eshop_favorate', '0003_alter_favorateitemdetail_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorateitem',
            options={'verbose_name': 'محصول مورد علاقه', 'verbose_name_plural': 'محصولات مورد علاقه'},
        ),
        migrations.AlterField(
            model_name='favorateitemdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
