# Generated by Django 3.2.3 on 2021-06-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favorate', '0004_auto_20210623_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorateitemdetail',
            name='favorateitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_favorate.favorateitem', verbose_name='سبد محصولات مورد علاقه کاربر '),
        ),
    ]
